# Generated by Django 6.0.5 on 2026-05-11 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0004_alter_contractattachment_options_and_more'),
        ('stages', '0002_remove_contractstage_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер акта')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата акта')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('signed', 'Подписан'), ('rejected', 'Отклонён'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='contracts.contract', verbose_name='Договор')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_acts', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acts', to='stages.contractstage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Акт',
                'verbose_name_plural': 'Акты',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['contract', 'stage', 'status'], name='acts_act_contrac_a21cfd_idx')],
            },
        ),
    ]
