# Generated by Django 6.0.5 on 2026-05-10 20:59

import django.db.models.deletion
from django.db import migrations, models


def create_organization_links(apps, schema_editor):
    Contractor = apps.get_model('contractors', 'Contractor')
    OrganizationContractor = apps.get_model('contractors', 'OrganizationContractor')

    for contractor in Contractor.objects.exclude(organization_id__isnull=True):
        OrganizationContractor.objects.get_or_create(
            organization_id=contractor.organization_id,
            contractor_id=contractor.id,
            defaults={'is_active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contractor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contractor',
            name='linked_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_cards', to='organizations.organization', verbose_name='Связанная организация'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='inn',
            field=models.CharField(db_index=True, max_length=12, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contractor_cards', to='organizations.organization', verbose_name='Организация-инициатор'),
        ),
        migrations.CreateModel(
            name='OrganizationContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная связь')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания по работе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='contractors.contractor', verbose_name='Контрагент')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_links', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Связь организации с контрагентом',
                'verbose_name_plural': 'Связи организаций с контрагентами',
                'ordering': ['organization', 'contractor'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'contractor'), name='unique_organization_contractor')],
            },
        ),
        migrations.RunPython(create_organization_links, migrations.RunPython.noop),
    ]
