# Generated by Django 6.0.5 on 2026-05-10 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер сметы')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('current_version', models.IntegerField(default=1, verbose_name='Текущая версия')),
                ('status', models.CharField(choices=[('draft', 'Проект'), ('active', 'Действует'), ('approved', 'Утверждена'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='contracts.contract', verbose_name='Договор')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Смета',
                'verbose_name_plural': 'Сметы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='Номер версии')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма')),
                ('file', models.FileField(blank=True, null=True, upload_to='estimates/', verbose_name='Файл')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Содержимое')),
                ('changelog', models.TextField(blank=True, verbose_name='Описание изменений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущая версия')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='estimates.estimate', verbose_name='Смета')),
            ],
            options={
                'verbose_name': 'Версия сметы',
                'verbose_name_plural': 'Версии смет',
                'ordering': ['-version_number'],
                'unique_together': {('estimate', 'version_number')},
            },
        ),
    ]
