# Generated by Django 6.0.5 on 2026-05-11 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
        ('stages', '0002_remove_contractstage_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='estimateversion',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='estimateversion',
            name='changelog',
        ),
        migrations.RemoveField(
            model_name='estimateversion',
            name='content',
        ),
        migrations.RemoveField(
            model_name='estimateversion',
            name='file',
        ),
        migrations.AddField(
            model_name='estimate',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='currency',
            field=models.CharField(default='RUB', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Итоговая сумма'),
        ),
        migrations.AddField(
            model_name='estimateversion',
            name='change_reason',
            field=models.TextField(blank=True, verbose_name='Причина изменения'),
        ),
        migrations.AddField(
            model_name='estimateversion',
            name='snapshot',
            field=models.JSONField(default=dict, verbose_name='Снимок данных'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('under_review', 'На проверке'), ('approved', 'Утверждена'), ('rejected', 'Отклонена'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='estimateversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Единица')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=15, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimates.estimate', verbose_name='Смета')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_items', to='stages.contractstage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Позиция сметы',
                'verbose_name_plural': 'Позиции сметы',
                'ordering': ['estimate', 'sort_order', 'id'],
            },
        ),
    ]
