# Generated by Django 6.0.5 on 2026-05-10 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма этапа')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершён')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='contracts.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Этап договора',
                'verbose_name_plural': 'Этапы договоров',
                'ordering': ['contract', 'order'],
            },
        ),
    ]
