# Generated by Django 6.0.5 on 2026-05-11 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractstage',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='contractstage',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='contractstage',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='contractstage',
            name='actual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Фактическая сумма'),
        ),
        migrations.AddField(
            model_name='contractstage',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическое окончание'),
        ),
        migrations.AddField(
            model_name='contractstage',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическое начало'),
        ),
        migrations.AddField(
            model_name='contractstage',
            name='planned_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Плановая сумма'),
        ),
        migrations.AddField(
            model_name='contractstage',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_stages', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='contractstage',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирован'), ('in_progress', 'В работе'), ('completed', 'Завершён'), ('delayed', 'Задержан'), ('cancelled', 'Отменён')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contractstage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядок'),
        ),
    ]
