# Generated by Django 6.0.5 on 2026-05-11 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('contract', 'Договор'), ('estimate', 'Смета'), ('stage', 'Этап'), ('act', 'Акт'), ('payment', 'Платёж')], max_length=20, verbose_name='Тип сущности')),
                ('entity_id', models.PositiveBigIntegerField(verbose_name='ID сущности')),
                ('category', models.CharField(choices=[('draft', 'Черновик'), ('final', 'Финальная версия'), ('signed', 'Подписанный документ'), ('scan', 'Скан-копия'), ('appendix', 'Приложение'), ('source', 'Исходный файл'), ('export', 'Экспорт'), ('invoice', 'Счёт'), ('act', 'Акт'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Категория')),
                ('file', models.FileField(upload_to='attachments/', verbose_name='Файл')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('mime_type', models.CharField(blank=True, max_length=120, verbose_name='MIME-тип')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Размер')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_attachments', to='organizations.organization', verbose_name='Организация')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['organization', 'entity_type', 'entity_id'], name='attachments_organiz_0fcb4a_idx'), models.Index(fields=['entity_type', 'entity_id', 'category'], name='attachments_entity__eb6ad4_idx')],
            },
        ),
    ]
