# Generated by Django 5.1.15 on 2026-05-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='entity_type',
            field=models.CharField(choices=[('contract', 'Договор'), ('estimate', 'Смета'), ('stage', 'Этап'), ('act', 'Акт'), ('payment', 'Платёж'), ('template', 'Шаблон')], max_length=20, verbose_name='Тип сущности'),
        ),
    ]
