import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { BadgeCheck, Clock3, Download, FileText, History, Plus, Receipt, Save, ShieldCheck, Trash2, WalletCards } from 'lucide-react';
import apiClient from '@/api/client';
import { useAuthStore } from '@/stores/authStore';
import { calculateContractDebt, calculateContractPaidAmount, calculateStageActualAmount, calculateStagePlannedAmount, formatContractPrice, formatDate, formatMoney, getResults, prettyJson } from '@/shared/lib/format';
import type { Act, ApprovalRoute, ApprovalTask, AuditLog, Comment, Contract, ContractPriceType, ContractStage, ContractStatus, ContractVersion, Contractor, Estimate, EstimateItem, EstimateStatus, FileAttachment, FileCategory, PaginatedResponse, Payment, PaymentStatus, PaymentType, ReferenceEntry, StageStatus, User } from '@/shared/types/domain';
import { actStatusOptions, contractStatusOptions, estimateStatusOptions, fileCategoryOptions, paymentStatusOptions, paymentTypeOptions, priceTypeOptions, stageStatusOptions } from '@/shared/types/domain';
import { Badge, Button, DataTable, EmptyState, Field, Input, LoadingBlock, PageIntro, SectionCard, Select, StatCard, Textarea } from '@/shared/components/ui';

interface ContractFormState { title: string; number: string; status: ContractStatus; contractor: string; price_type: ContractPriceType; amount: string; currency: string; start_date: string; end_date: string; signing_date: string; termination_date: string; payment_terms: string; description: string; responsible: string; }
interface StageFormState { name: string; order: string; status: StageStatus; planned_amount: string; start_date: string; end_date: string; description: string; }
interface ActFormState { stage: string; number: string; title: string; date: string; amount: string; status: string; description: string; }
interface PaymentFormState { stage: string; act: string; type: PaymentType; amount: string; planned_date: string; paid_date: string; status: PaymentStatus; description: string; }
interface EstimateFormState { title: string; number: string; status: EstimateStatus; currency: string; }
interface FileFormState { category: FileCategory; file: File | null; }

const emptyStage: StageFormState = { name: '', order: '1', status: 'planned', planned_amount: '', start_date: '', end_date: '', description: '' };
const emptyAct: ActFormState = { stage: '', number: '', title: '', date: '', amount: '', status: 'draft', description: '' };
const emptyPayment: PaymentFormState = { stage: '', act: '', type: 'planned', amount: '', planned_date: '', paid_date: '', status: 'pending', description: '' };
const emptyEstimate: EstimateFormState = { title: '', number: '', status: 'draft', currency: 'RUB' };
const emptyFile: FileFormState = { category: 'other', file: null };

function buildContractForm(contract: Contract): ContractFormState {
  return { title: contract.title, number: contract.number || '', status: contract.status, contractor: contract.contractor ? String(contract.contractor) : '', price_type: contract.price_type, amount: contract.amount == null ? '' : String(contract.amount), currency: contract.currency || 'RUB', start_date: contract.start_date || '', end_date: contract.end_date || '', signing_date: contract.signing_date || '', termination_date: contract.termination_date || '', payment_terms: contract.payment_terms || '', description: contract.description || '', responsible: contract.responsible ? String(contract.responsible) : '' };
}
function contractPayload(form: ContractFormState) {
  const hasAmount = form.amount.trim() !== '';
  return { title: form.title, number: form.number, status: form.status, contractor: form.contractor ? Number(form.contractor) : null, price_type: form.price_type, amount: form.price_type === 'not_specified' ? null : hasAmount ? Number(form.amount) : null, currency: hasAmount && form.price_type !== 'free' ? form.currency || 'RUB' : form.price_type === 'free' ? null : form.currency || null, start_date: form.start_date || null, end_date: form.end_date || null, signing_date: form.signing_date || null, termination_date: form.termination_date || null, payment_terms: form.payment_terms, description: form.description, responsible: form.responsible ? Number(form.responsible) : null };
}
function toneByStatus(status: string) { if (['active', 'approved', 'signed', 'completed', 'paid'].includes(status)) return 'success'; if (['on_approval', 'under_review', 'in_progress', 'pending'].includes(status)) return 'accent'; if (['terminated', 'rejected', 'cancelled', 'overdue', 'delayed'].includes(status)) return 'danger'; return 'neutral'; }
function fileSize(size?: number) { if (!size) return 'Размер не указан'; if (size < 1024 * 1024) return `${Math.round(size / 1024)} КБ`; return `${(size / 1024 / 1024).toFixed(1)} МБ`; }

function ContractDetailsContent(props: { contract: Contract; contractors: Contractor[]; users: User[]; versions: ContractVersion[]; comments: Comment[]; audit: AuditLog[]; stages: ContractStage[]; estimates: Estimate[]; payments: Payment[]; approvals: ApprovalTask[]; approvalRoutes: ApprovalRoute[]; files: FileAttachment[]; acts: Act[]; currencies: ReferenceEntry[]; }) {
  const { contract, contractors, users, versions, comments, audit, stages, estimates, payments, approvals, approvalRoutes, files, acts, currencies } = props;
  const contractId = contract.id;
  const queryClient = useQueryClient();
  const permissions = useAuthStore((state) => state.permissions);
  const canManageContracts = Boolean(permissions?.can_manage_contracts);
  const canManagePayments = Boolean(permissions?.can_manage_payments || permissions?.can_manage_contracts);
  const canLaunchApproval = Boolean(permissions?.can_launch_approval);
  const [form, setForm] = useState<ContractFormState>(buildContractForm(contract));
  const [stageForm, setStageForm] = useState<StageFormState>(emptyStage);
  const [actForm, setActForm] = useState<ActFormState>(emptyAct);
  const [paymentForm, setPaymentForm] = useState<PaymentFormState>(emptyPayment);
  const [estimateForm, setEstimateForm] = useState<EstimateFormState>(emptyEstimate);
  const [fileForm, setFileForm] = useState<FileFormState>(emptyFile);
  const [commentText, setCommentText] = useState('');
  const [approvalRouteId, setApprovalRouteId] = useState('');
  const [error, setError] = useState('');
  const estimateItems = useMemo(() => estimates.flatMap((estimate) => estimate.items ?? []) as EstimateItem[], [estimates]);
  const activeApprovalRoutes = approvalRoutes.filter((route) => route.is_active);
  const hasActiveApproval = approvals.some((task) => task.status === 'pending' || task.status === 'waiting');
  const selectedApprovalRouteId = approvalRouteId || String(activeApprovalRoutes[0]?.id || '');
  const currencyOptions = currencies.length ? currencies : [{ id: 0, code: contract.currency || 'RUB', label: contract.currency || 'RUB' } as ReferenceEntry];
  const paidAmount = calculateContractPaidAmount(contract, payments);
  const debt = calculateContractDebt(contract, acts, payments);
  const invalidateContract = async () => { await queryClient.invalidateQueries({ queryKey: ['contract', contractId] }); await queryClient.invalidateQueries({ queryKey: ['contracts'] }); await queryClient.invalidateQueries({ queryKey: ['contract', contractId, 'versions'] }); };

  const saveMutation = useMutation({ mutationFn: () => apiClient.patch(`/contracts/${contractId}/`, contractPayload(form)), onSuccess: invalidateContract, onError: () => setError('Не удалось сохранить карточку договора.') });
  const stageMutation = useMutation({ mutationFn: () => apiClient.post('/stages/', { contract: contractId, name: stageForm.name, order: Number(stageForm.order || 1), status: stageForm.status, planned_amount: stageForm.planned_amount ? Number(stageForm.planned_amount) : null, start_date: stageForm.start_date || null, end_date: stageForm.end_date || null, description: stageForm.description }), onSuccess: async () => { setStageForm(emptyStage); await queryClient.invalidateQueries({ queryKey: ['contract', contractId, 'stages'] }); } });
  const actMutation = useMutation({ mutationFn: () => apiClient.post('/acts/', { contract: contractId, stage: actForm.stage ? Number(actForm.stage) : null, number: actForm.number, title: actForm.title, date: actForm.date, amount: Number(actForm.amount || 0), status: actForm.status, description: actForm.description }), onSuccess: async () => { setActForm(emptyAct); await queryClient.invalidateQueries({ queryKey: ['contract', contractId, 'acts'] }); await queryClient.invalidateQueries({ queryKey: ['contract', contractId, 'stages'] }); } });
  const paymentMutation = useMutation({ mutationFn: () => apiClient.post('/payments/', { contract: contractId, stage: paymentForm.stage ? Number(paymentForm.stage) : null, act: paymentForm.act ? Number(paymentForm.act) : null, type: paymentForm.type, amount: Number(paymentForm.amount || 0), planned_date: paymentForm.planned_date || null, paid_date: paymentForm.paid_date || null, status: paymentForm.status, description: paymentForm.description }), onSuccess: async () => { setPaymentForm(emptyPayment); await queryClient.invalidateQueries({ queryKey: ['contract', contractId, 'payments'] }); } });
  const estimateMutation = useMutation({ mutationFn: () => apiClient.post('/estimates/', { contract: contractId, title: estimateForm.title, number: estimateForm.number, status: estimateForm.status, currency: estimateForm.currency }), onSuccess: async () => { setEstimateForm(emptyEstimate); await queryClient.invalidateQueries({ queryKey: ['contract', contractId, 'estimates'] }); } });
  const fileMutation = useMutation({ mutationFn: async () => { if (!fileForm.file) throw new Error('file-required'); const payload = new FormData(); payload.append('entity_type', 'contract'); payload.append('entity_id', String(contractId)); payload.append('category', fileForm.category); payload.append('file', fileForm.file); return apiClient.post('/file-attachments/', payload); }, onSuccess: async () => { setFileForm(emptyFile); await queryClient.invalidateQueries({ queryKey: ['contract', contractId, 'files'] }); }, onError: () => setError('Не удалось загрузить файл договора.') });
  const commentMutation = useMutation({ mutationFn: () => apiClient.post('/comments/', { contract: contractId, text: commentText, is_internal: false }), onSuccess: async () => { setCommentText(''); await queryClient.invalidateQueries({ queryKey: ['contract', contractId, 'comments'] }); } });
  const launchApprovalMutation = useMutation({ mutationFn: () => apiClient.post(`/contracts/${contractId}/launch_approval/`, { route_id: selectedApprovalRouteId ? Number(selectedApprovalRouteId) : undefined }), onSuccess: async () => { await invalidateContract(); await queryClient.invalidateQueries({ queryKey: ['contract', contractId, 'approvals'] }); await queryClient.invalidateQueries({ queryKey: ['approval-tasks'] }); }, onError: () => setError('Не удалось запустить маршрут согласования.') });

  return <div className="space-y-6">
    <PageIntro eyebrow="Договор" title={contract.title} actions={canManageContracts ? <Button onClick={() => saveMutation.mutate()} busy={saveMutation.isPending} className="rounded-2xl px-5 py-3"><Save className="h-4 w-4" />Сохранить</Button> : undefined} />
    <div className="grid gap-4 md:grid-cols-4">
      <StatCard label="Статус" value={contract.status_display || contractStatusOptions.find((item) => item.value === contract.status)?.label || contract.status} hint={`Версия v${contract.current_version}`} tone="brand" icon={<BadgeCheck className="h-5 w-5" />} />
      <StatCard label="Стоимость" value={formatContractPrice(contract, estimates)} hint={contract.contractor_name || 'Контрагент не выбран'} tone="accent" icon={<Receipt className="h-5 w-5" />} />
      <StatCard label="Оплачено" value={formatMoney(paidAmount, contract.currency || 'RUB')} hint={`Долг: ${formatMoney(debt, contract.currency || 'RUB')}`} tone="neutral" icon={<WalletCards className="h-5 w-5" />} />
      <StatCard label="Срок" value={contract.end_date ? formatDate(contract.end_date) : 'Не указан'} hint={contract.start_date ? `с ${formatDate(contract.start_date)}` : 'Дата начала не указана'} tone="neutral" icon={<Clock3 className="h-5 w-5" />} />
    </div>
    {error ? <div className="rounded-2xl border border-[rgba(180,79,64,0.18)] bg-[rgba(180,79,64,0.08)] px-4 py-3 text-sm text-[var(--danger)]">{error}</div> : null}

    <SectionCard title="Основная информация"><fieldset disabled={!canManageContracts} className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
      <Field label="Название"><Input value={form.title} onChange={(event) => setForm((current) => ({ ...current, title: event.target.value }))} /></Field>
      <Field label="Номер"><Input value={form.number} onChange={(event) => setForm((current) => ({ ...current, number: event.target.value }))} /></Field>
      <Field label="Статус"><Select value={form.status} onChange={(event) => setForm((current) => ({ ...current, status: event.target.value as ContractStatus }))}>{contractStatusOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</Select></Field>
      <Field label="Контрагент"><Select value={form.contractor} onChange={(event) => setForm((current) => ({ ...current, contractor: event.target.value }))}><option value="">Не выбран</option>{contractors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field>
      <Field label="Тип стоимости"><Select value={form.price_type} onChange={(event) => setForm((current) => ({ ...current, price_type: event.target.value as ContractPriceType }))}>{priceTypeOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</Select></Field>
      <Field label="Сумма"><Input type="number" value={form.amount} onChange={(event) => setForm((current) => ({ ...current, amount: event.target.value }))} placeholder="Можно оставить пустым" /></Field>
      <Field label="Валюта"><Select value={form.currency} onChange={(event) => setForm((current) => ({ ...current, currency: event.target.value }))}>{currencyOptions.map((currency) => <option key={currency.code} value={currency.code}>{currency.code} - {currency.label}</option>)}</Select></Field>
      <Field label="Дата начала"><Input type="date" value={form.start_date} onChange={(event) => setForm((current) => ({ ...current, start_date: event.target.value }))} /></Field>
      <Field label="Дата окончания"><Input type="date" value={form.end_date} onChange={(event) => setForm((current) => ({ ...current, end_date: event.target.value }))} /></Field>
      <Field label="Дата подписания"><Input type="date" value={form.signing_date} onChange={(event) => setForm((current) => ({ ...current, signing_date: event.target.value }))} /></Field>
      <Field label="Дата расторжения"><Input type="date" value={form.termination_date} onChange={(event) => setForm((current) => ({ ...current, termination_date: event.target.value }))} /></Field>
      <Field label="Ответственный"><Select value={form.responsible} onChange={(event) => setForm((current) => ({ ...current, responsible: event.target.value }))}><option value="">Не назначен</option>{users.map((item) => <option key={item.id} value={item.id}>{item.full_name || item.username}</option>)}</Select></Field>
      <div className="md:col-span-2 xl:col-span-3"><Field label="Условия оплаты"><Textarea value={form.payment_terms} onChange={(event) => setForm((current) => ({ ...current, payment_terms: event.target.value }))} /></Field></div>
      <div className="md:col-span-2 xl:col-span-3"><Field label="Описание"><Textarea value={form.description} onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))} /></Field></div>
    </fieldset></SectionCard>

    <SectionCard title="Документы" action={canManageContracts ? <Button onClick={() => fileMutation.mutate()} busy={fileMutation.isPending} disabled={!fileForm.file}>Прикрепить файл</Button> : undefined}>
      {canManageContracts ? <div className="mb-5 grid gap-4 md:grid-cols-[0.7fr_1.3fr]"><Field label="Категория"><Select value={fileForm.category} onChange={(event) => setFileForm((current) => ({ ...current, category: event.target.value as FileCategory }))}>{fileCategoryOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</Select></Field><Field label="Файл"><Input type="file" onChange={(event) => setFileForm((current) => ({ ...current, file: event.target.files?.[0] ?? null }))} /></Field></div> : null}
      {files.length ? <div className="grid gap-3 xl:grid-cols-2">{files.map((file) => <div key={file.id} className="rounded-[1.5rem] border border-[var(--line)] bg-white/75 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><Badge tone="neutral">{file.category_display || fileCategoryOptions.find((item) => item.value === file.category)?.label || file.category}</Badge><p className="mt-3 break-words text-sm font-semibold text-[var(--foreground)]">{file.file_name}</p><p className="mt-1 text-xs text-[var(--muted-foreground)]">{fileSize(file.size)} • {formatDate(file.uploaded_at, true)}</p></div><FileText className="h-5 w-5 shrink-0 text-[var(--brand)]" /></div><div className="mt-4 flex flex-wrap gap-3"><a href={file.file_url || file.file} download={file.file_name} className="inline-flex items-center justify-center gap-2 rounded-full border border-[var(--line)] bg-white/80 px-4 py-2.5 text-sm font-semibold text-[var(--foreground)] transition hover:border-[var(--line-strong)] hover:bg-white"><Download className="h-4 w-4" />Скачать</a>{canManageContracts ? <Button variant="ghost" onClick={async () => { if (confirm('Удалить файл?')) { await apiClient.delete(`/file-attachments/${file.id}/`); await queryClient.invalidateQueries({ queryKey: ['contract', contractId, 'files'] }); } }}><Trash2 className="h-4 w-4" />Удалить</Button> : null}</div></div>)}</div> : <EmptyState title="Файлы отсутствуют" />}
    </SectionCard>

    <SectionCard title="Сметы" action={canManageContracts ? <Button onClick={() => estimateMutation.mutate()} busy={estimateMutation.isPending}><Plus className="h-4 w-4" />Добавить смету</Button> : <Link to="/estimates"><Button variant="secondary">Открыть сметы</Button></Link>}>
      {canManageContracts ? <div className="mb-5 grid gap-4 md:grid-cols-2"><Field label="Название"><Input value={estimateForm.title} onChange={(event) => setEstimateForm((current) => ({ ...current, title: event.target.value }))} /></Field><Field label="Номер"><Input value={estimateForm.number} onChange={(event) => setEstimateForm((current) => ({ ...current, number: event.target.value }))} /></Field><Field label="Статус"><Select value={estimateForm.status} onChange={(event) => setEstimateForm((current) => ({ ...current, status: event.target.value as EstimateStatus }))}>{estimateStatusOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</Select></Field><Field label="Валюта"><Input value={estimateForm.currency} onChange={(event) => setEstimateForm((current) => ({ ...current, currency: event.target.value }))} /></Field></div> : null}
      {estimates.length ? <div className="space-y-4">{estimates.map((estimate) => <Link key={estimate.id} to={`/estimates/${estimate.id}`} className="block rounded-[1.5rem] border border-[var(--line)] bg-white/75 p-4 transition hover:border-[var(--line-strong)]"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><Badge tone={toneByStatus(estimate.status)}>{estimate.status_display || estimate.status}</Badge><Badge tone="neutral">{estimate.number || 'Без номера'}</Badge></div><h3 className="mt-3 text-base font-semibold text-[var(--foreground)]">{estimate.title}</h3><p className="mt-1 text-sm text-[var(--muted-foreground)]">Позиций: {estimate.items?.length ?? estimate.items_count ?? 0}</p></div><p className="font-semibold text-[var(--foreground)]">{formatMoney(estimate.total_amount ?? estimate.amount, estimate.currency || contract.currency || 'RUB')}</p></div>{estimate.items?.length ? <div className="mt-4 grid gap-2">{estimate.items.slice(0, 4).map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-2xl bg-white/70 px-4 py-2 text-sm"><span className="text-[var(--foreground)]">{item.name}</span><span className="text-[var(--muted-foreground)]">{item.stage_name || 'Без этапа'} • {formatMoney(item.total, estimate.currency)}</span></div>)}</div> : null}</Link>)}</div> : <EmptyState title="Сметы отсутствуют" />}
    </SectionCard>

    <div className="grid gap-6 xl:grid-cols-2">
      <SectionCard title="Этапы" action={canManageContracts ? <Button onClick={() => stageMutation.mutate()} busy={stageMutation.isPending}><Plus className="h-4 w-4" />Добавить этап</Button> : undefined}>
        {canManageContracts ? <div className="mb-5 grid gap-4 md:grid-cols-2"><Field label="Название"><Input value={stageForm.name} onChange={(event) => setStageForm((current) => ({ ...current, name: event.target.value }))} /></Field><Field label="Порядок"><Input type="number" value={stageForm.order} onChange={(event) => setStageForm((current) => ({ ...current, order: event.target.value }))} /></Field><Field label="Статус"><Select value={stageForm.status} onChange={(event) => setStageForm((current) => ({ ...current, status: event.target.value as StageStatus }))}>{stageStatusOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</Select></Field><Field label="Плановая сумма"><Input type="number" value={stageForm.planned_amount} onChange={(event) => setStageForm((current) => ({ ...current, planned_amount: event.target.value }))} /></Field><Field label="Дата начала"><Input type="date" value={stageForm.start_date} onChange={(event) => setStageForm((current) => ({ ...current, start_date: event.target.value }))} /></Field><Field label="Дата окончания"><Input type="date" value={stageForm.end_date} onChange={(event) => setStageForm((current) => ({ ...current, end_date: event.target.value }))} /></Field><div className="md:col-span-2"><Field label="Описание"><Textarea value={stageForm.description} onChange={(event) => setStageForm((current) => ({ ...current, description: event.target.value }))} /></Field></div></div> : null}
        {stages.length ? <div className="space-y-3">{stages.map((stage) => <div key={stage.id} className="rounded-[1.5rem] border border-[var(--line)] bg-white/75 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><Badge tone={toneByStatus(stage.status)}>{stage.status_display || stageStatusOptions.find((item) => item.value === stage.status)?.label || stage.status}</Badge><h3 className="mt-3 font-semibold text-[var(--foreground)]">{stage.order}. {stage.name}</h3><p className="mt-1 text-sm text-[var(--muted-foreground)]">{formatDate(stage.start_date)} - {formatDate(stage.end_date)}</p></div><div className="text-right text-sm"><p className="font-semibold text-[var(--foreground)]">План: {formatMoney(calculateStagePlannedAmount(stage, estimateItems), contract.currency || 'RUB')}</p><p className="mt-1 text-[var(--muted-foreground)]">Факт: {formatMoney(calculateStageActualAmount(stage, acts), contract.currency || 'RUB')}</p></div></div></div>)}</div> : <EmptyState title="Этапы отсутствуют" />}
      </SectionCard>

      <SectionCard title="Акты" action={canManageContracts ? <Button onClick={() => actMutation.mutate()} busy={actMutation.isPending}><Plus className="h-4 w-4" />Добавить акт</Button> : undefined}>
        {canManageContracts ? <div className="mb-5 grid gap-4 md:grid-cols-2"><Field label="Этап"><Select value={actForm.stage} onChange={(event) => setActForm((current) => ({ ...current, stage: event.target.value }))}><option value="">Без этапа</option>{stages.map((stage) => <option key={stage.id} value={stage.id}>{stage.name}</option>)}</Select></Field><Field label="Статус"><Select value={actForm.status} onChange={(event) => setActForm((current) => ({ ...current, status: event.target.value }))}>{actStatusOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</Select></Field><Field label="Номер"><Input value={actForm.number} onChange={(event) => setActForm((current) => ({ ...current, number: event.target.value }))} /></Field><Field label="Дата"><Input type="date" value={actForm.date} onChange={(event) => setActForm((current) => ({ ...current, date: event.target.value }))} /></Field><Field label="Название"><Input value={actForm.title} onChange={(event) => setActForm((current) => ({ ...current, title: event.target.value }))} /></Field><Field label="Сумма"><Input type="number" value={actForm.amount} onChange={(event) => setActForm((current) => ({ ...current, amount: event.target.value }))} /></Field></div> : null}
        {acts.length ? <DataTable columns={['Акт', 'Статус', 'Дата', 'Сумма']}>{acts.map((act) => <tr key={act.id} className="border-b border-[var(--line)] last:border-none"><td className="px-4 py-4"><p className="font-semibold text-[var(--foreground)]">{act.number}</p><p className="text-sm text-[var(--muted-foreground)]">{act.title}</p></td><td className="px-4 py-4"><Badge tone={toneByStatus(act.status)}>{act.status_display || act.status}</Badge></td><td className="px-4 py-4 text-[var(--muted-foreground)]">{formatDate(act.date)}</td><td className="px-4 py-4 text-[var(--foreground)]">{formatMoney(act.amount, contract.currency || 'RUB')}</td></tr>)}</DataTable> : <EmptyState title="Акты отсутствуют" />}
      </SectionCard>
    </div>

    <SectionCard title="Платежи" action={canManagePayments ? <Button onClick={() => paymentMutation.mutate()} busy={paymentMutation.isPending}><Plus className="h-4 w-4" />Добавить платёж</Button> : undefined}>
      {canManagePayments ? <div className="mb-5 grid gap-4 md:grid-cols-3"><Field label="Тип"><Select value={paymentForm.type} onChange={(event) => setPaymentForm((current) => ({ ...current, type: event.target.value as PaymentType }))}>{paymentTypeOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</Select></Field><Field label="Статус"><Select value={paymentForm.status} onChange={(event) => setPaymentForm((current) => ({ ...current, status: event.target.value as PaymentStatus }))}>{paymentStatusOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</Select></Field><Field label="Сумма"><Input type="number" value={paymentForm.amount} onChange={(event) => setPaymentForm((current) => ({ ...current, amount: event.target.value }))} /></Field><Field label="Этап"><Select value={paymentForm.stage} onChange={(event) => setPaymentForm((current) => ({ ...current, stage: event.target.value }))}><option value="">Без этапа</option>{stages.map((stage) => <option key={stage.id} value={stage.id}>{stage.name}</option>)}</Select></Field><Field label="Акт"><Select value={paymentForm.act} onChange={(event) => setPaymentForm((current) => ({ ...current, act: event.target.value }))}><option value="">Без акта</option>{acts.map((act) => <option key={act.id} value={act.id}>{act.number} - {act.title}</option>)}</Select></Field><Field label="Плановая дата"><Input type="date" value={paymentForm.planned_date} onChange={(event) => setPaymentForm((current) => ({ ...current, planned_date: event.target.value }))} /></Field><Field label="Дата оплаты"><Input type="date" value={paymentForm.paid_date} onChange={(event) => setPaymentForm((current) => ({ ...current, paid_date: event.target.value }))} /></Field><div className="md:col-span-2"><Field label="Описание"><Input value={paymentForm.description} onChange={(event) => setPaymentForm((current) => ({ ...current, description: event.target.value }))} /></Field></div></div> : null}
      {payments.length ? <DataTable columns={['Платёж', 'Связь', 'Дата', 'Сумма', 'Статус']}>{payments.map((payment) => <tr key={payment.id} className="border-b border-[var(--line)] last:border-none"><td className="px-4 py-4"><p className="font-semibold text-[var(--foreground)]">{payment.description || payment.type_display || payment.type}</p></td><td className="px-4 py-4 text-[var(--muted-foreground)]">{payment.act_title || payment.stage_name || 'По договору'}</td><td className="px-4 py-4 text-[var(--muted-foreground)]">{formatDate(payment.paid_date || payment.planned_date)}</td><td className="px-4 py-4 text-[var(--foreground)]">{formatMoney(payment.amount, contract.currency || 'RUB')}</td><td className="px-4 py-4"><Badge tone={toneByStatus(payment.status)}>{payment.status_display || payment.status}</Badge></td></tr>)}</DataTable> : <EmptyState title="Платежи отсутствуют" />}
    </SectionCard>

    <div className="grid gap-6 xl:grid-cols-2">
      <SectionCard title="Согласование" action={canLaunchApproval && activeApprovalRoutes.length ? <Button onClick={() => launchApprovalMutation.mutate()} busy={launchApprovalMutation.isPending} disabled={hasActiveApproval || !selectedApprovalRouteId}><ShieldCheck className="h-4 w-4" />Запустить маршрут</Button> : undefined}>
        {canLaunchApproval && activeApprovalRoutes.length ? <div className="mb-4"><Field label="Маршрут"><Select value={selectedApprovalRouteId} onChange={(event) => setApprovalRouteId(event.target.value)} disabled={hasActiveApproval}>{activeApprovalRoutes.map((route) => <option key={route.id} value={route.id}>{route.name}</option>)}</Select></Field></div> : null}
        {approvals.length ? <div className="space-y-3">{approvals.map((task) => <div key={task.id} className="rounded-[1.5rem] border border-[var(--line)] bg-white/75 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><Badge tone={toneByStatus(task.status)}>{task.status_display || task.status}</Badge><span className="text-xs text-[var(--muted-foreground)]">Шаг {task.stage_order}</span></div><p className="mt-3 font-semibold text-[var(--foreground)]">{task.assigned_to_name || task.role}</p><p className="mt-1 text-sm text-[var(--muted-foreground)]">{task.comment || 'Комментарий не добавлен'}</p></div>)}</div> : <EmptyState title="Задачи согласования отсутствуют" />}
      </SectionCard>
      <SectionCard title="История версий">
        {versions.length ? <div className="space-y-3">{versions.map((version) => <details key={version.id} className="rounded-[1.5rem] border border-[var(--line)] bg-white/75 p-4"><summary className="cursor-pointer font-semibold text-[var(--foreground)]">v{version.version_number} {version.is_current ? '· текущая' : ''}</summary><p className="mt-2 text-xs text-[var(--muted-foreground)]">{version.created_by_name || 'Система'} • {formatDate(version.created_at, true)}</p><p className="mt-3 text-sm text-[var(--muted-foreground)]">{version.change_reason || 'Причина не указана'}</p><pre className="mt-3 max-h-72 overflow-auto rounded-2xl bg-[var(--muted)] p-4 text-xs text-[var(--foreground)]">{prettyJson(version.snapshot)}</pre></details>)}</div> : <EmptyState title="Версии отсутствуют" />}
      </SectionCard>
    </div>

    <div className="grid gap-6 xl:grid-cols-2">
      <SectionCard title="Комментарии" action={<Button onClick={() => commentMutation.mutate()} busy={commentMutation.isPending} disabled={!commentText.trim()}>Добавить</Button>}>
        <Field label="Комментарий"><Textarea value={commentText} onChange={(event) => setCommentText(event.target.value)} /></Field>
        <div className="mt-4 space-y-3">{comments.length ? comments.map((comment) => <div key={comment.id} className="rounded-[1.5rem] border border-[var(--line)] bg-white/75 p-4"><p className="font-semibold text-[var(--foreground)]">{comment.author_name || 'Пользователь'}</p><p className="mt-1 text-xs text-[var(--muted-foreground)]">{formatDate(comment.created_at, true)}</p><p className="mt-3 text-sm text-[var(--muted-foreground)]">{comment.text}</p></div>) : <EmptyState title="Комментариев нет" />}</div>
      </SectionCard>
      <SectionCard title="Журнал действий">
        {audit.length ? <div className="space-y-3">{audit.map((entry) => <div key={entry.id} className="rounded-[1.5rem] border border-[var(--line)] bg-white/75 p-4"><div className="flex items-center gap-2"><History className="h-4 w-4 text-[var(--brand)]" /><p className="font-semibold text-[var(--foreground)]">{entry.description || entry.action}</p></div><p className="mt-2 text-xs text-[var(--muted-foreground)]">{entry.user_name || 'Система'} • {formatDate(entry.created_at, true)}</p></div>)}</div> : <EmptyState title="Записей аудита нет" />}
      </SectionCard>
    </div>
  </div>;
}

export default function ContractDetailsPage() {
  const { id } = useParams();
  const contractId = Number(id);
  const permissions = useAuthStore((state) => state.permissions);
  const canManageContracts = Boolean(permissions?.can_manage_contracts);
  const enabled = Number.isFinite(contractId);
  const { data: contract, isLoading: contractLoading } = useQuery<Contract>({ queryKey: ['contract', contractId], queryFn: () => apiClient.get(`/contracts/${contractId}/`).then((response) => response.data), enabled });
  const { data: versionsPayload } = useQuery<PaginatedResponse<ContractVersion>>({ queryKey: ['contract', contractId, 'versions'], queryFn: () => apiClient.get(`/contracts/${contractId}/versions/`).then((response) => response.data), enabled });
  const { data: commentsPayload } = useQuery<PaginatedResponse<Comment>>({ queryKey: ['contract', contractId, 'comments'], queryFn: () => apiClient.get('/comments/', { params: { contract: contractId } }).then((response) => response.data), enabled });
  const { data: auditPayload } = useQuery<PaginatedResponse<AuditLog>>({ queryKey: ['contract', contractId, 'audit'], queryFn: () => apiClient.get('/audit-logs/', { params: { entity_type: 'Contract', entity_id: contractId } }).then((response) => response.data), enabled });
  const { data: stagesPayload } = useQuery<PaginatedResponse<ContractStage>>({ queryKey: ['contract', contractId, 'stages'], queryFn: () => apiClient.get('/stages/', { params: { contract: contractId } }).then((response) => response.data), enabled });
  const { data: estimatesPayload } = useQuery<PaginatedResponse<Estimate>>({ queryKey: ['contract', contractId, 'estimates'], queryFn: () => apiClient.get('/estimates/', { params: { contract: contractId } }).then((response) => response.data), enabled });
  const { data: paymentsPayload } = useQuery<PaginatedResponse<Payment>>({ queryKey: ['contract', contractId, 'payments'], queryFn: () => apiClient.get('/payments/', { params: { contract: contractId } }).then((response) => response.data), enabled });
  const { data: actsPayload } = useQuery<PaginatedResponse<Act>>({ queryKey: ['contract', contractId, 'acts'], queryFn: () => apiClient.get('/acts/', { params: { contract: contractId } }).then((response) => response.data), enabled });
  const { data: approvalsPayload } = useQuery<PaginatedResponse<ApprovalTask>>({ queryKey: ['contract', contractId, 'approvals'], queryFn: () => apiClient.get('/approval-tasks/', { params: { contract: contractId } }).then((response) => response.data), enabled });
  const { data: approvalRoutesPayload } = useQuery<PaginatedResponse<ApprovalRoute>>({ queryKey: ['contract-detail', 'approval-routes'], queryFn: () => apiClient.get('/approval-routes/').then((response) => response.data) });
  const { data: filesPayload } = useQuery<PaginatedResponse<FileAttachment>>({ queryKey: ['contract', contractId, 'files'], queryFn: () => apiClient.get('/file-attachments/', { params: { entity_type: 'contract', entity_id: contractId } }).then((response) => response.data), enabled });
  const { data: contractorsPayload } = useQuery<PaginatedResponse<Contractor>>({ queryKey: ['contract-detail', 'contractors'], queryFn: () => apiClient.get('/contractors/').then((response) => response.data), enabled: canManageContracts });
  const { data: usersPayload } = useQuery<PaginatedResponse<User>>({ queryKey: ['contract-detail', 'users'], queryFn: () => apiClient.get('/users/').then((response) => response.data), enabled: canManageContracts });
  const { data: currenciesPayload } = useQuery<PaginatedResponse<ReferenceEntry>>({ queryKey: ['contract-detail', 'currencies'], queryFn: () => apiClient.get('/reference-entries/', { params: { category: 'currency', is_active: true } }).then((response) => response.data), enabled: canManageContracts });
  if (contractLoading || !contract) return <LoadingBlock label="Открываем карточку договора..." />;
  return <ContractDetailsContent key={contract.id} contract={contract} contractors={getResults(contractorsPayload)} users={getResults(usersPayload)} versions={getResults(versionsPayload)} comments={getResults(commentsPayload)} audit={getResults(auditPayload)} stages={getResults(stagesPayload)} estimates={getResults(estimatesPayload)} payments={getResults(paymentsPayload)} approvals={getResults(approvalsPayload)} approvalRoutes={getResults(approvalRoutesPayload)} files={getResults(filesPayload)} acts={getResults(actsPayload)} currencies={getResults(currenciesPayload)} />;
}
