# Generated by Django 6.0.5 on 2026-05-10 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('content', models.JSONField(default=dict, verbose_name='Содержимое шаблона (JSON)')),
                ('contract_type', models.CharField(default='standard', max_length=50, verbose_name='Тип договора')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='Переменные шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Шаблон договора',
                'verbose_name_plural': 'Шаблоны договоров',
                'ordering': ['name'],
            },
        ),
    ]
