# Generated by Django 6.0.5 on 2026-05-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='templates/', verbose_name='DOCX-файл шаблона'),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='content',
            field=models.JSONField(blank=True, default=dict, verbose_name='Служебное содержимое'),
        ),
    ]
