# Generated by Django 6.0.5 on 2026-05-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_contracttemplate_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracttemplate',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contracttemplate',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='contracttemplate',
            name='variables',
        ),
    ]
