# Generated by Django 6.0.5 on 2026-05-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_remove_contracttemplate_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttemplate',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='templates/', verbose_name='Файл шаблона'),
        ),
    ]
