# Generated by Django 6.0.5 on 2026-05-10 14:42

import django.db.models.deletion
from django.db import migrations, models


def bootstrap_reference_entries(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    ReferenceEntry = apps.get_model('references', 'ReferenceEntry')

    defaults = {
        'currency': [
            {'code': 'RUB', 'label': 'Российский рубль', 'description': 'Базовая валюта расчётов', 'metadata': {'rate': 1}},
            {'code': 'USD', 'label': 'Доллар США', 'description': 'Валютный расчёт по экспортным и импортным контрактам', 'metadata': {'rate': 92}},
            {'code': 'EUR', 'label': 'Евро', 'description': 'Валютный расчёт по международным обязательствам', 'metadata': {'rate': 101}},
            {'code': 'CNY', 'label': 'Китайский юань', 'description': 'Расчёты по поставкам из КНР', 'metadata': {'rate': 12.8}},
        ],
        'contract_type': [
            {'code': 'standard', 'label': 'Стандартный', 'description': 'Базовый шаблон универсального договора'},
            {'code': 'service', 'label': 'Оказание услуг', 'description': 'Договор на оказание услуг'},
            {'code': 'supply', 'label': 'Поставка', 'description': 'Договор поставки товаров и оборудования'},
            {'code': 'lease', 'label': 'Аренда', 'description': 'Договор аренды имущества'},
            {'code': 'nda', 'label': 'NDA', 'description': 'Соглашение о конфиденциальности'},
            {'code': 'labor', 'label': 'Подряд / трудовой', 'description': 'Договор подряда или трудовой договор'},
            {'code': 'other', 'label': 'Прочее', 'description': 'Иные виды договоров'},
        ],
        'contract_status': [
            {'code': 'draft', 'label': 'Проект', 'description': 'Документ создан и находится в подготовке'},
            {'code': 'approval', 'label': 'На согласовании', 'description': 'Документ передан на экспертизу и утверждение'},
            {'code': 'active', 'label': 'Действует', 'description': 'Договор утверждён и вступил в силу'},
            {'code': 'execution', 'label': 'Исполнение', 'description': 'Договор исполняется по этапам и платежам'},
            {'code': 'closed', 'label': 'Закрыт', 'description': 'Обязательства исполнены и закрыты'},
            {'code': 'archived', 'label': 'Архив', 'description': 'Документ переведён в архив'},
        ],
    }

    for organization in Organization.objects.all():
        for category, entries in defaults.items():
            for index, entry in enumerate(entries, start=1):
                ReferenceEntry.objects.get_or_create(
                    organization=organization,
                    category=category,
                    code=entry['code'],
                    defaults={
                        'label': entry['label'],
                        'description': entry['description'],
                        'metadata': entry.get('metadata', {}),
                        'is_active': True,
                        'sort_order': index * 10,
                    },
                )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('currency', 'Валюты'), ('contract_type', 'Типы договоров'), ('contract_status', 'Статусы договоров')], max_length=40, verbose_name='Категория')),
                ('code', models.CharField(max_length=60, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные параметры')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_entries', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочников',
                'ordering': ['category', 'sort_order', 'label'],
                'unique_together': {('organization', 'category', 'code')},
            },
        ),
        migrations.RunPython(bootstrap_reference_entries, migrations.RunPython.noop),
    ]
