# Generated by Django 6.0.5 on 2026-05-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceentry',
            name='category',
            field=models.CharField(choices=[('currency', 'Валюты'), ('price_type', 'Типы стоимости'), ('contract_status', 'Статусы договоров')], max_length=40, verbose_name='Категория'),
        ),
    ]
