# Generated by Django 6.0.5 on 2026-05-10 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('estimates', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('planned', 'Плановый'), ('actual', 'Фактический')], max_length=20, verbose_name='Тип платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата')),
                ('status', models.CharField(choices=[('pending', 'Ожидается'), ('paid', 'Оплачен'), ('overdue', 'Просрочен'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Назначение платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract', verbose_name='Договор')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='estimates.estimate', verbose_name='Смета')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц')),
                ('total_planned', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='План')),
                ('total_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Факт')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Задолженность')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_calendars', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Календарь платежей',
                'verbose_name_plural': 'Календари платежей',
                'ordering': ['-month'],
                'unique_together': {('organization', 'month')},
            },
        ),
    ]
