# Generated by Django 6.0.5 on 2026-05-10 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
        ('organizations', '0001_initial'),
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('status', models.CharField(choices=[('draft', 'Проект'), ('approval', 'На согласовании'), ('active', 'Действует'), ('execution', 'Исполнение'), ('closed', 'Закрыт'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('contract_type', models.CharField(choices=[('standard', 'Стандартный'), ('service', 'Услуги'), ('supply', 'Поставка'), ('lease', 'Аренда'), ('nda', 'NDA'), ('labor', 'Трудовой'), ('other', 'Прочее')], default='standard', max_length=20, verbose_name='Тип договора')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('current_version', models.IntegerField(default=1, verbose_name='Текущая версия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contractors.contractor', verbose_name='Контрагент')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='organizations.organization', verbose_name='Организация')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.contracttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='Номер версии')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма')),
                ('content', models.JSONField(default=dict, verbose_name='Содержимое')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Файл')),
                ('changelog', models.TextField(blank=True, verbose_name='Описание изменений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущая версия')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contracts.contract', verbose_name='Договор')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Версия договора',
                'verbose_name_plural': 'Версии договоров',
                'ordering': ['-version_number'],
                'unique_together': {('contract', 'version_number')},
            },
        ),
    ]
