# Generated by Django 6.0.5 on 2026-05-10 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('document_type', models.CharField(choices=[('scan', 'Скан-копия'), ('addendum', 'Дополнительное соглашение'), ('act', 'Акт'), ('invoice', 'Счёт'), ('estimate', 'Смета'), ('other', 'Прочий документ')], default='other', max_length=20, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='contract_attachments/', verbose_name='Файл')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contracts.contract', verbose_name='Договор')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Вложение договора',
                'verbose_name_plural': 'Вложения договоров',
                'ordering': ['-created_at'],
            },
        ),
    ]
