# Generated by Django 6.0.5 on 2026-05-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contractattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_type',
        ),
    ]
