# Generated by Django 6.0.5 on 2026-05-11 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_contract_contract_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractattachment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Вложение договора (старое)', 'verbose_name_plural': 'Вложения договоров (старые)'},
        ),
        migrations.RemoveField(
            model_name='contractversion',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='contractversion',
            name='changelog',
        ),
        migrations.RemoveField(
            model_name='contractversion',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contractversion',
            name='file',
        ),
        migrations.RemoveField(
            model_name='contractversion',
            name='number',
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_terms',
            field=models.TextField(blank=True, verbose_name='Условия оплаты'),
        ),
        migrations.AddField(
            model_name='contract',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная стоимость'), ('estimate_based', 'По сметам'), ('free', 'Безвозмездный'), ('not_specified', 'Стоимость не указана'), ('by_rates', 'По тарифам/актам/заявкам')], default='not_specified', max_length=20, verbose_name='Тип стоимости'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подписания'),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата расторжения'),
        ),
        migrations.AddField(
            model_name='contractversion',
            name='change_reason',
            field=models.TextField(blank=True, verbose_name='Причина изменения'),
        ),
        migrations.AddField(
            model_name='contractversion',
            name='snapshot',
            field=models.JSONField(default=dict, verbose_name='Снимок данных'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(blank=True, default='RUB', max_length=3, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На согласовании'), ('ready_to_sign', 'Готов к подписанию'), ('signed', 'Подписан'), ('active', 'Действует'), ('completed', 'Завершён'), ('terminated', 'Расторгнут')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contractattachment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_attachments', to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='contractattachment',
            name='document_type',
            field=models.CharField(choices=[('scan', 'Скан-копия'), ('appendix', 'Приложение'), ('act', 'Акт'), ('invoice', 'Счёт'), ('source', 'Сметный файл'), ('other', 'Прочий документ')], default='other', max_length=20, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='contractversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
    ]
