# Generated by Django 6.0.5 on 2026-05-10 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название маршрута')),
                ('contract_types', models.CharField(blank=True, max_length=255, verbose_name='Типы договоров (JSON)')),
                ('stages', models.JSONField(default=list, verbose_name='Этапы согласования')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_routes', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Маршрут согласования',
                'verbose_name_plural': 'Маршруты согласования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_order', models.IntegerField(verbose_name='Порядок этапа')),
                ('role', models.CharField(max_length=20, verbose_name='Роль согласующего')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Согласован'), ('rejected', 'Отклонён'), ('skipped', 'Пропущен')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Назначен')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tasks', to='contracts.contract', verbose_name='Договор')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='approvals.approvalroute', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Задача согласования',
                'verbose_name_plural': 'Задачи согласования',
                'ordering': ['contract', 'stage_order'],
            },
        ),
    ]
