# Generated by Django 6.0.5 on 2026-05-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltask',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок согласования'),
        ),
    ]
