# Generated by Django 6.0.5 on 2026-05-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_approvaltask_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalroute',
            name='contract_types',
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидает очереди'), ('pending', 'Ожидает'), ('approved', 'Согласован'), ('rejected', 'Отклонён'), ('skipped', 'Пропущен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
