# Generated by Django 6.0.5 on 2026-05-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_remove_approvalroute_contract_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltask',
            name='role',
            field=models.CharField(max_length=80, verbose_name='Роль согласующего'),
        ),
    ]
